
include ..\COM_LNK\MakeSDK.1

TARGET  = Operation

PROGNAME = "Operation"

VERSION = 0102

MICON = menuicon\icon.bmp

LICON = menuicon\Licon.bmp

APLOBJS =	$(ODIR)\Op.obj

HEADFILE = 	$(HDIR)\Op.h

include ..\COM_LNK\MakeSDK.2


